/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CourseService } from "../course.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CourseCreateInput } from "./CourseCreateInput";
import { Course } from "./Course";
import { CourseFindManyArgs } from "./CourseFindManyArgs";
import { CourseWhereUniqueInput } from "./CourseWhereUniqueInput";
import { CourseUpdateInput } from "./CourseUpdateInput";
import { CourseLecturerFindManyArgs } from "../../courseLecturer/base/CourseLecturerFindManyArgs";
import { CourseLecturer } from "../../courseLecturer/base/CourseLecturer";
import { CourseLecturerWhereUniqueInput } from "../../courseLecturer/base/CourseLecturerWhereUniqueInput";
import { CourseSessionFindManyArgs } from "../../courseSession/base/CourseSessionFindManyArgs";
import { CourseSession } from "../../courseSession/base/CourseSession";
import { CourseSessionWhereUniqueInput } from "../../courseSession/base/CourseSessionWhereUniqueInput";
import { LecturerFindManyArgs } from "../../lecturer/base/LecturerFindManyArgs";
import { Lecturer } from "../../lecturer/base/Lecturer";
import { LecturerWhereUniqueInput } from "../../lecturer/base/LecturerWhereUniqueInput";
import { ScheduleCourseFindManyArgs } from "../../scheduleCourse/base/ScheduleCourseFindManyArgs";
import { ScheduleCourse } from "../../scheduleCourse/base/ScheduleCourse";
import { ScheduleCourseWhereUniqueInput } from "../../scheduleCourse/base/ScheduleCourseWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CourseControllerBase {
  constructor(
    protected readonly service: CourseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Course })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCourse(@common.Body() data: CourseCreateInput): Promise<Course> {
    return await this.service.createCourse({
      data: {
        ...data,

        department: {
          connect: data.department,
        },
      },
      select: {
        capacity: true,
        code: true,
        createdAt: true,
        credit: true,

        department: {
          select: {
            id: true,
          },
        },

        examDate: true,
        grade: true,
        group: true,
        id: true,
        info: true,
        name: true,
        numberOfEnrolled: true,
        numberOfPetitioners: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Course] })
  @ApiNestedQuery(CourseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async courses(@common.Req() request: Request): Promise<Course[]> {
    const args = plainToClass(CourseFindManyArgs, request.query);
    return this.service.courses({
      ...args,
      select: {
        capacity: true,
        code: true,
        createdAt: true,
        credit: true,

        department: {
          select: {
            id: true,
          },
        },

        examDate: true,
        grade: true,
        group: true,
        id: true,
        info: true,
        name: true,
        numberOfEnrolled: true,
        numberOfPetitioners: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Course })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async course(
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<Course | null> {
    const result = await this.service.course({
      where: params,
      select: {
        capacity: true,
        code: true,
        createdAt: true,
        credit: true,

        department: {
          select: {
            id: true,
          },
        },

        examDate: true,
        grade: true,
        group: true,
        id: true,
        info: true,
        name: true,
        numberOfEnrolled: true,
        numberOfPetitioners: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Course })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCourse(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() data: CourseUpdateInput
  ): Promise<Course | null> {
    try {
      return await this.service.updateCourse({
        where: params,
        data: {
          ...data,

          department: {
            connect: data.department,
          },
        },
        select: {
          capacity: true,
          code: true,
          createdAt: true,
          credit: true,

          department: {
            select: {
              id: true,
            },
          },

          examDate: true,
          grade: true,
          group: true,
          id: true,
          info: true,
          name: true,
          numberOfEnrolled: true,
          numberOfPetitioners: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Course })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCourse(
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<Course | null> {
    try {
      return await this.service.deleteCourse({
        where: params,
        select: {
          capacity: true,
          code: true,
          createdAt: true,
          credit: true,

          department: {
            select: {
              id: true,
            },
          },

          examDate: true,
          grade: true,
          group: true,
          id: true,
          info: true,
          name: true,
          numberOfEnrolled: true,
          numberOfPetitioners: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/courseLecturers")
  @ApiNestedQuery(CourseLecturerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "read",
    possession: "any",
  })
  async findCourseLecturers(
    @common.Req() request: Request,
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<CourseLecturer[]> {
    const query = plainToClass(CourseLecturerFindManyArgs, request.query);
    const results = await this.service.findCourseLecturers(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        lecturer: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/courseLecturers")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async connectCourseLecturers(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: CourseLecturerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseLecturers: {
        connect: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/courseLecturers")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async updateCourseLecturers(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: CourseLecturerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseLecturers: {
        set: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/courseLecturers")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async disconnectCourseLecturers(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: CourseLecturerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseLecturers: {
        disconnect: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/courseSessions")
  @ApiNestedQuery(CourseSessionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CourseSession",
    action: "read",
    possession: "any",
  })
  async findCourseSessions(
    @common.Req() request: Request,
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<CourseSession[]> {
    const query = plainToClass(CourseSessionFindManyArgs, request.query);
    const results = await this.service.findCourseSessions(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dayOfWeek: true,
        endTime: true,
        id: true,
        startTime: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/courseSessions")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async connectCourseSessions(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: CourseSessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseSessions: {
        connect: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/courseSessions")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async updateCourseSessions(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: CourseSessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseSessions: {
        set: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/courseSessions")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async disconnectCourseSessions(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: CourseSessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseSessions: {
        disconnect: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/lecturer")
  @ApiNestedQuery(LecturerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "read",
    possession: "any",
  })
  async findLecturer(
    @common.Req() request: Request,
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<Lecturer[]> {
    const query = plainToClass(LecturerFindManyArgs, request.query);
    const results = await this.service.findLecturer(params.id, {
      ...query,
      select: {
        createdAt: true,

        department: {
          select: {
            id: true,
          },
        },

        examDifficultyRating: true,
        fullName: true,
        id: true,
        moralityRating: true,
        numberOfReviews: true,
        pressureRating: true,
        rating: true,
        teachingRating: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/lecturer")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async connectLecturer(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: LecturerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lecturer: {
        connect: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/lecturer")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async updateLecturer(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: LecturerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lecturer: {
        set: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/lecturer")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async disconnectLecturer(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: LecturerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lecturer: {
        disconnect: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/scheduleCourses")
  @ApiNestedQuery(ScheduleCourseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ScheduleCourse",
    action: "read",
    possession: "any",
  })
  async findScheduleCourses(
    @common.Req() request: Request,
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<ScheduleCourse[]> {
    const query = plainToClass(ScheduleCourseFindManyArgs, request.query);
    const results = await this.service.findScheduleCourses(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        schedule: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/scheduleCourses")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async connectScheduleCourses(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: ScheduleCourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scheduleCourses: {
        connect: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/scheduleCourses")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async updateScheduleCourses(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: ScheduleCourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scheduleCourses: {
        set: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/scheduleCourses")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async disconnectScheduleCourses(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: ScheduleCourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scheduleCourses: {
        disconnect: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }
}
