/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  IsOptional,
  IsString,
  ValidateNested,
  IsDate,
  IsEnum,
} from "class-validator";
import { CourseLecturerUpdateManyWithoutCoursesInput } from "./CourseLecturerUpdateManyWithoutCoursesInput";
import { Type } from "class-transformer";
import { CourseSessionUpdateManyWithoutCoursesInput } from "./CourseSessionUpdateManyWithoutCoursesInput";
import { DepartmentWhereUniqueInput } from "../../department/base/DepartmentWhereUniqueInput";
import { EnumCourseGrade } from "./EnumCourseGrade";
import { LecturerUpdateManyWithoutCoursesInput } from "./LecturerUpdateManyWithoutCoursesInput";
import { ScheduleCourseUpdateManyWithoutCoursesInput } from "./ScheduleCourseUpdateManyWithoutCoursesInput";

@InputType()
class CourseUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  capacity?: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  code?: string;

  @ApiProperty({
    required: false,
    type: () => CourseLecturerUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => CourseLecturerUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => CourseLecturerUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  courseLecturers?: CourseLecturerUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => CourseSessionUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => CourseSessionUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => CourseSessionUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  courseSessions?: CourseSessionUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  credit?: number;

  @ApiProperty({
    required: false,
    type: () => DepartmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DepartmentWhereUniqueInput)
  @IsOptional()
  @Field(() => DepartmentWhereUniqueInput, {
    nullable: true,
  })
  department?: DepartmentWhereUniqueInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  examDate?: Date;

  @ApiProperty({
    required: false,
    enum: EnumCourseGrade,
  })
  @IsEnum(EnumCourseGrade)
  @IsOptional()
  @Field(() => EnumCourseGrade, {
    nullable: true,
  })
  grade?: "BSC" | "MSC" | "PhD" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  group?: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  info?: string | null;

  @ApiProperty({
    required: false,
    type: () => LecturerUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => LecturerUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => LecturerUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  lecturer?: LecturerUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  numberOfEnrolled?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  numberOfPetitioners?: number | null;

  @ApiProperty({
    required: false,
    type: () => ScheduleCourseUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => ScheduleCourseUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => ScheduleCourseUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  scheduleCourses?: ScheduleCourseUpdateManyWithoutCoursesInput;
}

export { CourseUpdateInput as CourseUpdateInput };
