/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  IsString,
  ValidateNested,
  IsOptional,
  IsDate,
  IsEnum,
} from "class-validator";
import { CourseLecturer } from "../../courseLecturer/base/CourseLecturer";
import { Type } from "class-transformer";
import { CourseSession } from "../../courseSession/base/CourseSession";
import { Department } from "../../department/base/Department";
import { EnumCourseGrade } from "./EnumCourseGrade";
import { Lecturer } from "../../lecturer/base/Lecturer";
import { ScheduleCourse } from "../../scheduleCourse/base/ScheduleCourse";

@ObjectType()
class Course {
  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  capacity!: number;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  code!: string;

  @ApiProperty({
    required: false,
    type: () => [CourseLecturer],
  })
  @ValidateNested()
  @Type(() => CourseLecturer)
  @IsOptional()
  courseLecturers?: Array<CourseLecturer>;

  @ApiProperty({
    required: false,
    type: () => [CourseSession],
  })
  @ValidateNested()
  @Type(() => CourseSession)
  @IsOptional()
  courseSessions?: Array<CourseSession>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  credit!: number;

  @ApiProperty({
    required: true,
    type: () => Department,
  })
  @ValidateNested()
  @Type(() => Department)
  department?: Department;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  examDate!: Date;

  @ApiProperty({
    required: false,
    enum: EnumCourseGrade,
  })
  @IsEnum(EnumCourseGrade)
  @IsOptional()
  @Field(() => EnumCourseGrade, {
    nullable: true,
  })
  grade?: "BSC" | "MSC" | "PhD" | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  group!: number;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  info!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Lecturer],
  })
  @ValidateNested()
  @Type(() => Lecturer)
  @IsOptional()
  lecturer?: Array<Lecturer>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  numberOfEnrolled!: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  numberOfPetitioners!: number | null;

  @ApiProperty({
    required: false,
    type: () => [ScheduleCourse],
  })
  @ValidateNested()
  @Type(() => ScheduleCourse)
  @IsOptional()
  scheduleCourses?: Array<ScheduleCourse>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Course as Course };
