/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Course, // @ts-ignore
  CourseLecturer, // @ts-ignore
  CourseSession, // @ts-ignore
  Lecturer, // @ts-ignore
  ScheduleCourse, // @ts-ignore
  Department,
} from "@prisma/client";

export class CourseServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CourseCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseCountArgs>
  ): Promise<number> {
    return this.prisma.course.count(args);
  }

  async courses<T extends Prisma.CourseFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseFindManyArgs>
  ): Promise<Course[]> {
    return this.prisma.course.findMany(args);
  }
  async course<T extends Prisma.CourseFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseFindUniqueArgs>
  ): Promise<Course | null> {
    return this.prisma.course.findUnique(args);
  }
  async createCourse<T extends Prisma.CourseCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseCreateArgs>
  ): Promise<Course> {
    return this.prisma.course.create<T>(args);
  }
  async updateCourse<T extends Prisma.CourseUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseUpdateArgs>
  ): Promise<Course> {
    return this.prisma.course.update<T>(args);
  }
  async deleteCourse<T extends Prisma.CourseDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseDeleteArgs>
  ): Promise<Course> {
    return this.prisma.course.delete(args);
  }

  async findCourseLecturers(
    parentId: string,
    args: Prisma.CourseLecturerFindManyArgs
  ): Promise<CourseLecturer[]> {
    return this.prisma.course
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .courseLecturers(args);
  }

  async findCourseSessions(
    parentId: string,
    args: Prisma.CourseSessionFindManyArgs
  ): Promise<CourseSession[]> {
    return this.prisma.course
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .courseSessions(args);
  }

  async findLecturer(
    parentId: string,
    args: Prisma.LecturerFindManyArgs
  ): Promise<Lecturer[]> {
    return this.prisma.course
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .lecturer(args);
  }

  async findScheduleCourses(
    parentId: string,
    args: Prisma.ScheduleCourseFindManyArgs
  ): Promise<ScheduleCourse[]> {
    return this.prisma.course
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .scheduleCourses(args);
  }

  async getDepartment(parentId: string): Promise<Department | null> {
    return this.prisma.course
      .findUnique({
        where: { id: parentId },
      })
      .department();
  }
}
