/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  IsString,
  ValidateNested,
  IsOptional,
  IsDate,
  IsEnum,
} from "class-validator";
import { CourseLecturerCreateNestedManyWithoutCoursesInput } from "./CourseLecturerCreateNestedManyWithoutCoursesInput";
import { Type } from "class-transformer";
import { CourseSessionCreateNestedManyWithoutCoursesInput } from "./CourseSessionCreateNestedManyWithoutCoursesInput";
import { DepartmentWhereUniqueInput } from "../../department/base/DepartmentWhereUniqueInput";
import { EnumCourseGrade } from "./EnumCourseGrade";
import { LecturerCreateNestedManyWithoutCoursesInput } from "./LecturerCreateNestedManyWithoutCoursesInput";
import { ScheduleCourseCreateNestedManyWithoutCoursesInput } from "./ScheduleCourseCreateNestedManyWithoutCoursesInput";

@InputType()
class CourseCreateInput {
  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  capacity!: number;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  code!: string;

  @ApiProperty({
    required: false,
    type: () => CourseLecturerCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => CourseLecturerCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => CourseLecturerCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  courseLecturers?: CourseLecturerCreateNestedManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => CourseSessionCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => CourseSessionCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => CourseSessionCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  courseSessions?: CourseSessionCreateNestedManyWithoutCoursesInput;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  credit!: number;

  @ApiProperty({
    required: true,
    type: () => DepartmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DepartmentWhereUniqueInput)
  @Field(() => DepartmentWhereUniqueInput)
  department!: DepartmentWhereUniqueInput;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  examDate!: Date;

  @ApiProperty({
    required: false,
    enum: EnumCourseGrade,
  })
  @IsEnum(EnumCourseGrade)
  @IsOptional()
  @Field(() => EnumCourseGrade, {
    nullable: true,
  })
  grade?: "BSC" | "MSC" | "PhD" | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  group!: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  info?: string | null;

  @ApiProperty({
    required: false,
    type: () => LecturerCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => LecturerCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => LecturerCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  lecturer?: LecturerCreateNestedManyWithoutCoursesInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  numberOfEnrolled?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  numberOfPetitioners?: number | null;

  @ApiProperty({
    required: false,
    type: () => ScheduleCourseCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => ScheduleCourseCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => ScheduleCourseCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  scheduleCourses?: ScheduleCourseCreateNestedManyWithoutCoursesInput;
}

export { CourseCreateInput as CourseCreateInput };
