/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { CourseLecturerListRelationFilter } from "../../courseLecturer/base/CourseLecturerListRelationFilter";
import { CourseSessionListRelationFilter } from "../../courseSession/base/CourseSessionListRelationFilter";
import { DepartmentWhereUniqueInput } from "../../department/base/DepartmentWhereUniqueInput";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { EnumCourseGrade } from "./EnumCourseGrade";
import { IntFilter } from "../../util/IntFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { LecturerListRelationFilter } from "../../lecturer/base/LecturerListRelationFilter";
import { ScheduleCourseListRelationFilter } from "../../scheduleCourse/base/ScheduleCourseListRelationFilter";

@InputType()
class CourseWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  code?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => CourseLecturerListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CourseLecturerListRelationFilter)
  @IsOptional()
  @Field(() => CourseLecturerListRelationFilter, {
    nullable: true,
  })
  courseLecturers?: CourseLecturerListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => CourseSessionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CourseSessionListRelationFilter)
  @IsOptional()
  @Field(() => CourseSessionListRelationFilter, {
    nullable: true,
  })
  courseSessions?: CourseSessionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DepartmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DepartmentWhereUniqueInput)
  @IsOptional()
  @Field(() => DepartmentWhereUniqueInput, {
    nullable: true,
  })
  department?: DepartmentWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  examDate?: DateTimeFilter;

  @ApiProperty({
    required: false,
    enum: EnumCourseGrade,
  })
  @IsEnum(EnumCourseGrade)
  @IsOptional()
  @Field(() => EnumCourseGrade, {
    nullable: true,
  })
  grade?: "BSC" | "MSC" | "PhD";

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  group?: IntFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  info?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => LecturerListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LecturerListRelationFilter)
  @IsOptional()
  @Field(() => LecturerListRelationFilter, {
    nullable: true,
  })
  lecturer?: LecturerListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  name?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => ScheduleCourseListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScheduleCourseListRelationFilter)
  @IsOptional()
  @Field(() => ScheduleCourseListRelationFilter, {
    nullable: true,
  })
  scheduleCourses?: ScheduleCourseListRelationFilter;
}

export { CourseWhereInput as CourseWhereInput };
