/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ReviewLike } from "./ReviewLike";
import { ReviewLikeCountArgs } from "./ReviewLikeCountArgs";
import { ReviewLikeFindManyArgs } from "./ReviewLikeFindManyArgs";
import { ReviewLikeFindUniqueArgs } from "./ReviewLikeFindUniqueArgs";
import { CreateReviewLikeArgs } from "./CreateReviewLikeArgs";
import { UpdateReviewLikeArgs } from "./UpdateReviewLikeArgs";
import { DeleteReviewLikeArgs } from "./DeleteReviewLikeArgs";
import { Review } from "../../review/base/Review";
import { User } from "../../user/base/User";
import { ReviewLikeService } from "../reviewLike.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ReviewLike)
export class ReviewLikeResolverBase {
  constructor(
    protected readonly service: ReviewLikeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ReviewLike",
    action: "read",
    possession: "any",
  })
  async _reviewLikesMeta(
    @graphql.Args() args: ReviewLikeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ReviewLike])
  @nestAccessControl.UseRoles({
    resource: "ReviewLike",
    action: "read",
    possession: "any",
  })
  async reviewLikes(
    @graphql.Args() args: ReviewLikeFindManyArgs
  ): Promise<ReviewLike[]> {
    return this.service.reviewLikes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ReviewLike, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ReviewLike",
    action: "read",
    possession: "own",
  })
  async reviewLike(
    @graphql.Args() args: ReviewLikeFindUniqueArgs
  ): Promise<ReviewLike | null> {
    const result = await this.service.reviewLike(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ReviewLike)
  @nestAccessControl.UseRoles({
    resource: "ReviewLike",
    action: "create",
    possession: "any",
  })
  async createReviewLike(
    @graphql.Args() args: CreateReviewLikeArgs
  ): Promise<ReviewLike> {
    return await this.service.createReviewLike({
      ...args,
      data: {
        ...args.data,

        review: args.data.review
          ? {
              connect: args.data.review,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ReviewLike)
  @nestAccessControl.UseRoles({
    resource: "ReviewLike",
    action: "update",
    possession: "any",
  })
  async updateReviewLike(
    @graphql.Args() args: UpdateReviewLikeArgs
  ): Promise<ReviewLike | null> {
    try {
      return await this.service.updateReviewLike({
        ...args,
        data: {
          ...args.data,

          review: args.data.review
            ? {
                connect: args.data.review,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ReviewLike)
  @nestAccessControl.UseRoles({
    resource: "ReviewLike",
    action: "delete",
    possession: "any",
  })
  async deleteReviewLike(
    @graphql.Args() args: DeleteReviewLikeArgs
  ): Promise<ReviewLike | null> {
    try {
      return await this.service.deleteReviewLike(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Review, {
    nullable: true,
    name: "review",
  })
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "read",
    possession: "any",
  })
  async getReview(
    @graphql.Parent() parent: ReviewLike
  ): Promise<Review | null> {
    const result = await this.service.getReview(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: ReviewLike): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
