/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReviewLikeService } from "../reviewLike.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReviewLikeCreateInput } from "./ReviewLikeCreateInput";
import { ReviewLike } from "./ReviewLike";
import { ReviewLikeFindManyArgs } from "./ReviewLikeFindManyArgs";
import { ReviewLikeWhereUniqueInput } from "./ReviewLikeWhereUniqueInput";
import { ReviewLikeUpdateInput } from "./ReviewLikeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReviewLikeControllerBase {
  constructor(
    protected readonly service: ReviewLikeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ReviewLike })
  @nestAccessControl.UseRoles({
    resource: "ReviewLike",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createReviewLike(
    @common.Body() data: ReviewLikeCreateInput
  ): Promise<ReviewLike> {
    return await this.service.createReviewLike({
      data: {
        ...data,

        review: data.review
          ? {
              connect: data.review,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        like: true,

        review: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ReviewLike] })
  @ApiNestedQuery(ReviewLikeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ReviewLike",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reviewLikes(@common.Req() request: Request): Promise<ReviewLike[]> {
    const args = plainToClass(ReviewLikeFindManyArgs, request.query);
    return this.service.reviewLikes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        like: true,

        review: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ReviewLike })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReviewLike",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reviewLike(
    @common.Param() params: ReviewLikeWhereUniqueInput
  ): Promise<ReviewLike | null> {
    const result = await this.service.reviewLike({
      where: params,
      select: {
        createdAt: true,
        id: true,
        like: true,

        review: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ReviewLike })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReviewLike",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateReviewLike(
    @common.Param() params: ReviewLikeWhereUniqueInput,
    @common.Body() data: ReviewLikeUpdateInput
  ): Promise<ReviewLike | null> {
    try {
      return await this.service.updateReviewLike({
        where: params,
        data: {
          ...data,

          review: data.review
            ? {
                connect: data.review,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          like: true,

          review: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ReviewLike })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReviewLike",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReviewLike(
    @common.Param() params: ReviewLikeWhereUniqueInput
  ): Promise<ReviewLike | null> {
    try {
      return await this.service.deleteReviewLike({
        where: params,
        select: {
          createdAt: true,
          id: true,
          like: true,

          review: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
