/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ReviewLike, // @ts-ignore
  Review, // @ts-ignore
  User,
} from "@prisma/client";

export class ReviewLikeServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.ReviewLikeCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.ReviewLikeCountArgs>
  ): Promise<number> {
    return this.prisma.reviewLike.count(args);
  }

  async reviewLikes<T extends Prisma.ReviewLikeFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ReviewLikeFindManyArgs>
  ): Promise<ReviewLike[]> {
    return this.prisma.reviewLike.findMany(args);
  }
  async reviewLike<T extends Prisma.ReviewLikeFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ReviewLikeFindUniqueArgs>
  ): Promise<ReviewLike | null> {
    return this.prisma.reviewLike.findUnique(args);
  }
  async createReviewLike<T extends Prisma.ReviewLikeCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ReviewLikeCreateArgs>
  ): Promise<ReviewLike> {
    return this.prisma.reviewLike.create<T>(args);
  }
  async updateReviewLike<T extends Prisma.ReviewLikeUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ReviewLikeUpdateArgs>
  ): Promise<ReviewLike> {
    return this.prisma.reviewLike.update<T>(args);
  }
  async deleteReviewLike<T extends Prisma.ReviewLikeDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ReviewLikeDeleteArgs>
  ): Promise<ReviewLike> {
    return this.prisma.reviewLike.delete(args);
  }

  async getReview(parentId: string): Promise<Review | null> {
    return this.prisma.reviewLike
      .findUnique({
        where: { id: parentId },
      })
      .review();
  }

  async getUser(parentId: string): Promise<User | null> {
    return this.prisma.reviewLike
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
