/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CourseSessionService } from "../courseSession.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CourseSessionCreateInput } from "./CourseSessionCreateInput";
import { CourseSession } from "./CourseSession";
import { CourseSessionFindManyArgs } from "./CourseSessionFindManyArgs";
import { CourseSessionWhereUniqueInput } from "./CourseSessionWhereUniqueInput";
import { CourseSessionUpdateInput } from "./CourseSessionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CourseSessionControllerBase {
  constructor(
    protected readonly service: CourseSessionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CourseSession })
  @nestAccessControl.UseRoles({
    resource: "CourseSession",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCourseSession(
    @common.Body() data: CourseSessionCreateInput
  ): Promise<CourseSession> {
    return await this.service.createCourseSession({
      data: {
        ...data,

        course: {
          connect: data.course,
        },
      },
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dayOfWeek: true,
        endTime: true,
        id: true,
        startTime: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CourseSession] })
  @ApiNestedQuery(CourseSessionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CourseSession",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async courseSessions(
    @common.Req() request: Request
  ): Promise<CourseSession[]> {
    const args = plainToClass(CourseSessionFindManyArgs, request.query);
    return this.service.courseSessions({
      ...args,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dayOfWeek: true,
        endTime: true,
        id: true,
        startTime: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CourseSession })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CourseSession",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async courseSession(
    @common.Param() params: CourseSessionWhereUniqueInput
  ): Promise<CourseSession | null> {
    const result = await this.service.courseSession({
      where: params,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dayOfWeek: true,
        endTime: true,
        id: true,
        startTime: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CourseSession })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CourseSession",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCourseSession(
    @common.Param() params: CourseSessionWhereUniqueInput,
    @common.Body() data: CourseSessionUpdateInput
  ): Promise<CourseSession | null> {
    try {
      return await this.service.updateCourseSession({
        where: params,
        data: {
          ...data,

          course: {
            connect: data.course,
          },
        },
        select: {
          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          dayOfWeek: true,
          endTime: true,
          id: true,
          startTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CourseSession })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CourseSession",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCourseSession(
    @common.Param() params: CourseSessionWhereUniqueInput
  ): Promise<CourseSession | null> {
    try {
      return await this.service.deleteCourseSession({
        where: params,
        select: {
          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          dayOfWeek: true,
          endTime: true,
          id: true,
          startTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
