/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CourseSession } from "./CourseSession";
import { CourseSessionCountArgs } from "./CourseSessionCountArgs";
import { CourseSessionFindManyArgs } from "./CourseSessionFindManyArgs";
import { CourseSessionFindUniqueArgs } from "./CourseSessionFindUniqueArgs";
import { CreateCourseSessionArgs } from "./CreateCourseSessionArgs";
import { UpdateCourseSessionArgs } from "./UpdateCourseSessionArgs";
import { DeleteCourseSessionArgs } from "./DeleteCourseSessionArgs";
import { Course } from "../../course/base/Course";
import { CourseSessionService } from "../courseSession.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CourseSession)
export class CourseSessionResolverBase {
  constructor(
    protected readonly service: CourseSessionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CourseSession",
    action: "read",
    possession: "any",
  })
  async _courseSessionsMeta(
    @graphql.Args() args: CourseSessionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CourseSession])
  @nestAccessControl.UseRoles({
    resource: "CourseSession",
    action: "read",
    possession: "any",
  })
  async courseSessions(
    @graphql.Args() args: CourseSessionFindManyArgs
  ): Promise<CourseSession[]> {
    return this.service.courseSessions(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CourseSession, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CourseSession",
    action: "read",
    possession: "own",
  })
  async courseSession(
    @graphql.Args() args: CourseSessionFindUniqueArgs
  ): Promise<CourseSession | null> {
    const result = await this.service.courseSession(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CourseSession)
  @nestAccessControl.UseRoles({
    resource: "CourseSession",
    action: "create",
    possession: "any",
  })
  async createCourseSession(
    @graphql.Args() args: CreateCourseSessionArgs
  ): Promise<CourseSession> {
    return await this.service.createCourseSession({
      ...args,
      data: {
        ...args.data,

        course: {
          connect: args.data.course,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CourseSession)
  @nestAccessControl.UseRoles({
    resource: "CourseSession",
    action: "update",
    possession: "any",
  })
  async updateCourseSession(
    @graphql.Args() args: UpdateCourseSessionArgs
  ): Promise<CourseSession | null> {
    try {
      return await this.service.updateCourseSession({
        ...args,
        data: {
          ...args.data,

          course: {
            connect: args.data.course,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CourseSession)
  @nestAccessControl.UseRoles({
    resource: "CourseSession",
    action: "delete",
    possession: "any",
  })
  async deleteCourseSession(
    @graphql.Args() args: DeleteCourseSessionArgs
  ): Promise<CourseSession | null> {
    try {
      return await this.service.deleteCourseSession(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Course, {
    nullable: true,
    name: "course",
  })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "read",
    possession: "any",
  })
  async getCourse(
    @graphql.Parent() parent: CourseSession
  ): Promise<Course | null> {
    const result = await this.service.getCourse(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
