/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  CourseSession, // @ts-ignore
  Course,
} from "@prisma/client";

export class CourseSessionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CourseSessionCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseSessionCountArgs>
  ): Promise<number> {
    return this.prisma.courseSession.count(args);
  }

  async courseSessions<T extends Prisma.CourseSessionFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseSessionFindManyArgs>
  ): Promise<CourseSession[]> {
    return this.prisma.courseSession.findMany(args);
  }
  async courseSession<T extends Prisma.CourseSessionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseSessionFindUniqueArgs>
  ): Promise<CourseSession | null> {
    return this.prisma.courseSession.findUnique(args);
  }
  async createCourseSession<T extends Prisma.CourseSessionCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseSessionCreateArgs>
  ): Promise<CourseSession> {
    return this.prisma.courseSession.create<T>(args);
  }
  async updateCourseSession<T extends Prisma.CourseSessionUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseSessionUpdateArgs>
  ): Promise<CourseSession> {
    return this.prisma.courseSession.update<T>(args);
  }
  async deleteCourseSession<T extends Prisma.CourseSessionDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseSessionDeleteArgs>
  ): Promise<CourseSession> {
    return this.prisma.courseSession.delete(args);
  }

  async getCourse(parentId: string): Promise<Course | null> {
    return this.prisma.courseSession
      .findUnique({
        where: { id: parentId },
      })
      .course();
  }
}
