/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ScheduleCourse, // @ts-ignore
  Course, // @ts-ignore
  Schedule,
} from "@prisma/client";

export class ScheduleCourseServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.ScheduleCourseCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.ScheduleCourseCountArgs>
  ): Promise<number> {
    return this.prisma.scheduleCourse.count(args);
  }

  async scheduleCourses<T extends Prisma.ScheduleCourseFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ScheduleCourseFindManyArgs>
  ): Promise<ScheduleCourse[]> {
    return this.prisma.scheduleCourse.findMany(args);
  }
  async scheduleCourse<T extends Prisma.ScheduleCourseFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ScheduleCourseFindUniqueArgs>
  ): Promise<ScheduleCourse | null> {
    return this.prisma.scheduleCourse.findUnique(args);
  }
  async createScheduleCourse<T extends Prisma.ScheduleCourseCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ScheduleCourseCreateArgs>
  ): Promise<ScheduleCourse> {
    return this.prisma.scheduleCourse.create<T>(args);
  }
  async updateScheduleCourse<T extends Prisma.ScheduleCourseUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ScheduleCourseUpdateArgs>
  ): Promise<ScheduleCourse> {
    return this.prisma.scheduleCourse.update<T>(args);
  }
  async deleteScheduleCourse<T extends Prisma.ScheduleCourseDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ScheduleCourseDeleteArgs>
  ): Promise<ScheduleCourse> {
    return this.prisma.scheduleCourse.delete(args);
  }

  async getCourse(parentId: string): Promise<Course | null> {
    return this.prisma.scheduleCourse
      .findUnique({
        where: { id: parentId },
      })
      .course();
  }

  async getSchedule(parentId: string): Promise<Schedule | null> {
    return this.prisma.scheduleCourse
      .findUnique({
        where: { id: parentId },
      })
      .schedule();
  }
}
