/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ScheduleCourse } from "./ScheduleCourse";
import { ScheduleCourseCountArgs } from "./ScheduleCourseCountArgs";
import { ScheduleCourseFindManyArgs } from "./ScheduleCourseFindManyArgs";
import { ScheduleCourseFindUniqueArgs } from "./ScheduleCourseFindUniqueArgs";
import { CreateScheduleCourseArgs } from "./CreateScheduleCourseArgs";
import { UpdateScheduleCourseArgs } from "./UpdateScheduleCourseArgs";
import { DeleteScheduleCourseArgs } from "./DeleteScheduleCourseArgs";
import { Course } from "../../course/base/Course";
import { Schedule } from "../../schedule/base/Schedule";
import { ScheduleCourseService } from "../scheduleCourse.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ScheduleCourse)
export class ScheduleCourseResolverBase {
  constructor(
    protected readonly service: ScheduleCourseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ScheduleCourse",
    action: "read",
    possession: "any",
  })
  async _scheduleCoursesMeta(
    @graphql.Args() args: ScheduleCourseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ScheduleCourse])
  @nestAccessControl.UseRoles({
    resource: "ScheduleCourse",
    action: "read",
    possession: "any",
  })
  async scheduleCourses(
    @graphql.Args() args: ScheduleCourseFindManyArgs
  ): Promise<ScheduleCourse[]> {
    return this.service.scheduleCourses(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ScheduleCourse, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ScheduleCourse",
    action: "read",
    possession: "own",
  })
  async scheduleCourse(
    @graphql.Args() args: ScheduleCourseFindUniqueArgs
  ): Promise<ScheduleCourse | null> {
    const result = await this.service.scheduleCourse(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ScheduleCourse)
  @nestAccessControl.UseRoles({
    resource: "ScheduleCourse",
    action: "create",
    possession: "any",
  })
  async createScheduleCourse(
    @graphql.Args() args: CreateScheduleCourseArgs
  ): Promise<ScheduleCourse> {
    return await this.service.createScheduleCourse({
      ...args,
      data: {
        ...args.data,

        course: {
          connect: args.data.course,
        },

        schedule: {
          connect: args.data.schedule,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ScheduleCourse)
  @nestAccessControl.UseRoles({
    resource: "ScheduleCourse",
    action: "update",
    possession: "any",
  })
  async updateScheduleCourse(
    @graphql.Args() args: UpdateScheduleCourseArgs
  ): Promise<ScheduleCourse | null> {
    try {
      return await this.service.updateScheduleCourse({
        ...args,
        data: {
          ...args.data,

          course: {
            connect: args.data.course,
          },

          schedule: {
            connect: args.data.schedule,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ScheduleCourse)
  @nestAccessControl.UseRoles({
    resource: "ScheduleCourse",
    action: "delete",
    possession: "any",
  })
  async deleteScheduleCourse(
    @graphql.Args() args: DeleteScheduleCourseArgs
  ): Promise<ScheduleCourse | null> {
    try {
      return await this.service.deleteScheduleCourse(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Course, {
    nullable: true,
    name: "course",
  })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "read",
    possession: "any",
  })
  async getCourse(
    @graphql.Parent() parent: ScheduleCourse
  ): Promise<Course | null> {
    const result = await this.service.getCourse(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Schedule, {
    nullable: true,
    name: "schedule",
  })
  @nestAccessControl.UseRoles({
    resource: "Schedule",
    action: "read",
    possession: "any",
  })
  async getSchedule(
    @graphql.Parent() parent: ScheduleCourse
  ): Promise<Schedule | null> {
    const result = await this.service.getSchedule(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
