/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ScheduleCourseService } from "../scheduleCourse.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ScheduleCourseCreateInput } from "./ScheduleCourseCreateInput";
import { ScheduleCourse } from "./ScheduleCourse";
import { ScheduleCourseFindManyArgs } from "./ScheduleCourseFindManyArgs";
import { ScheduleCourseWhereUniqueInput } from "./ScheduleCourseWhereUniqueInput";
import { ScheduleCourseUpdateInput } from "./ScheduleCourseUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ScheduleCourseControllerBase {
  constructor(
    protected readonly service: ScheduleCourseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ScheduleCourse })
  @nestAccessControl.UseRoles({
    resource: "ScheduleCourse",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createScheduleCourse(
    @common.Body() data: ScheduleCourseCreateInput
  ): Promise<ScheduleCourse> {
    return await this.service.createScheduleCourse({
      data: {
        ...data,

        course: {
          connect: data.course,
        },

        schedule: {
          connect: data.schedule,
        },
      },
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        schedule: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ScheduleCourse] })
  @ApiNestedQuery(ScheduleCourseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ScheduleCourse",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async scheduleCourses(
    @common.Req() request: Request
  ): Promise<ScheduleCourse[]> {
    const args = plainToClass(ScheduleCourseFindManyArgs, request.query);
    return this.service.scheduleCourses({
      ...args,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        schedule: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ScheduleCourse })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ScheduleCourse",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async scheduleCourse(
    @common.Param() params: ScheduleCourseWhereUniqueInput
  ): Promise<ScheduleCourse | null> {
    const result = await this.service.scheduleCourse({
      where: params,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        schedule: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ScheduleCourse })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ScheduleCourse",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateScheduleCourse(
    @common.Param() params: ScheduleCourseWhereUniqueInput,
    @common.Body() data: ScheduleCourseUpdateInput
  ): Promise<ScheduleCourse | null> {
    try {
      return await this.service.updateScheduleCourse({
        where: params,
        data: {
          ...data,

          course: {
            connect: data.course,
          },

          schedule: {
            connect: data.schedule,
          },
        },
        select: {
          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          schedule: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ScheduleCourse })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ScheduleCourse",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteScheduleCourse(
    @common.Param() params: ScheduleCourseWhereUniqueInput
  ): Promise<ScheduleCourse | null> {
    try {
      return await this.service.deleteScheduleCourse({
        where: params,
        select: {
          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          schedule: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
