/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CourseLecturer } from "./CourseLecturer";
import { CourseLecturerCountArgs } from "./CourseLecturerCountArgs";
import { CourseLecturerFindManyArgs } from "./CourseLecturerFindManyArgs";
import { CourseLecturerFindUniqueArgs } from "./CourseLecturerFindUniqueArgs";
import { CreateCourseLecturerArgs } from "./CreateCourseLecturerArgs";
import { UpdateCourseLecturerArgs } from "./UpdateCourseLecturerArgs";
import { DeleteCourseLecturerArgs } from "./DeleteCourseLecturerArgs";
import { Course } from "../../course/base/Course";
import { Lecturer } from "../../lecturer/base/Lecturer";
import { CourseLecturerService } from "../courseLecturer.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CourseLecturer)
export class CourseLecturerResolverBase {
  constructor(
    protected readonly service: CourseLecturerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "read",
    possession: "any",
  })
  async _courseLecturersMeta(
    @graphql.Args() args: CourseLecturerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CourseLecturer])
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "read",
    possession: "any",
  })
  async courseLecturers(
    @graphql.Args() args: CourseLecturerFindManyArgs
  ): Promise<CourseLecturer[]> {
    return this.service.courseLecturers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CourseLecturer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "read",
    possession: "own",
  })
  async courseLecturer(
    @graphql.Args() args: CourseLecturerFindUniqueArgs
  ): Promise<CourseLecturer | null> {
    const result = await this.service.courseLecturer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CourseLecturer)
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "create",
    possession: "any",
  })
  async createCourseLecturer(
    @graphql.Args() args: CreateCourseLecturerArgs
  ): Promise<CourseLecturer> {
    return await this.service.createCourseLecturer({
      ...args,
      data: {
        ...args.data,

        course: {
          connect: args.data.course,
        },

        lecturer: {
          connect: args.data.lecturer,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CourseLecturer)
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "update",
    possession: "any",
  })
  async updateCourseLecturer(
    @graphql.Args() args: UpdateCourseLecturerArgs
  ): Promise<CourseLecturer | null> {
    try {
      return await this.service.updateCourseLecturer({
        ...args,
        data: {
          ...args.data,

          course: {
            connect: args.data.course,
          },

          lecturer: {
            connect: args.data.lecturer,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CourseLecturer)
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "delete",
    possession: "any",
  })
  async deleteCourseLecturer(
    @graphql.Args() args: DeleteCourseLecturerArgs
  ): Promise<CourseLecturer | null> {
    try {
      return await this.service.deleteCourseLecturer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Course, {
    nullable: true,
    name: "course",
  })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "read",
    possession: "any",
  })
  async getCourse(
    @graphql.Parent() parent: CourseLecturer
  ): Promise<Course | null> {
    const result = await this.service.getCourse(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Lecturer, {
    nullable: true,
    name: "lecturer",
  })
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "read",
    possession: "any",
  })
  async getLecturer(
    @graphql.Parent() parent: CourseLecturer
  ): Promise<Lecturer | null> {
    const result = await this.service.getLecturer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
