/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  CourseLecturer, // @ts-ignore
  Course, // @ts-ignore
  Lecturer,
} from "@prisma/client";

export class CourseLecturerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CourseLecturerCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseLecturerCountArgs>
  ): Promise<number> {
    return this.prisma.courseLecturer.count(args);
  }

  async courseLecturers<T extends Prisma.CourseLecturerFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseLecturerFindManyArgs>
  ): Promise<CourseLecturer[]> {
    return this.prisma.courseLecturer.findMany(args);
  }
  async courseLecturer<T extends Prisma.CourseLecturerFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseLecturerFindUniqueArgs>
  ): Promise<CourseLecturer | null> {
    return this.prisma.courseLecturer.findUnique(args);
  }
  async createCourseLecturer<T extends Prisma.CourseLecturerCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseLecturerCreateArgs>
  ): Promise<CourseLecturer> {
    return this.prisma.courseLecturer.create<T>(args);
  }
  async updateCourseLecturer<T extends Prisma.CourseLecturerUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseLecturerUpdateArgs>
  ): Promise<CourseLecturer> {
    return this.prisma.courseLecturer.update<T>(args);
  }
  async deleteCourseLecturer<T extends Prisma.CourseLecturerDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourseLecturerDeleteArgs>
  ): Promise<CourseLecturer> {
    return this.prisma.courseLecturer.delete(args);
  }

  async getCourse(parentId: string): Promise<Course | null> {
    return this.prisma.courseLecturer
      .findUnique({
        where: { id: parentId },
      })
      .course();
  }

  async getLecturer(parentId: string): Promise<Lecturer | null> {
    return this.prisma.courseLecturer
      .findUnique({
        where: { id: parentId },
      })
      .lecturer();
  }
}
