/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CourseLecturerService } from "../courseLecturer.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CourseLecturerCreateInput } from "./CourseLecturerCreateInput";
import { CourseLecturer } from "./CourseLecturer";
import { CourseLecturerFindManyArgs } from "./CourseLecturerFindManyArgs";
import { CourseLecturerWhereUniqueInput } from "./CourseLecturerWhereUniqueInput";
import { CourseLecturerUpdateInput } from "./CourseLecturerUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CourseLecturerControllerBase {
  constructor(
    protected readonly service: CourseLecturerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CourseLecturer })
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCourseLecturer(
    @common.Body() data: CourseLecturerCreateInput
  ): Promise<CourseLecturer> {
    return await this.service.createCourseLecturer({
      data: {
        ...data,

        course: {
          connect: data.course,
        },

        lecturer: {
          connect: data.lecturer,
        },
      },
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        lecturer: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CourseLecturer] })
  @ApiNestedQuery(CourseLecturerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async courseLecturers(
    @common.Req() request: Request
  ): Promise<CourseLecturer[]> {
    const args = plainToClass(CourseLecturerFindManyArgs, request.query);
    return this.service.courseLecturers({
      ...args,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        lecturer: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CourseLecturer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async courseLecturer(
    @common.Param() params: CourseLecturerWhereUniqueInput
  ): Promise<CourseLecturer | null> {
    const result = await this.service.courseLecturer({
      where: params,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        lecturer: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CourseLecturer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCourseLecturer(
    @common.Param() params: CourseLecturerWhereUniqueInput,
    @common.Body() data: CourseLecturerUpdateInput
  ): Promise<CourseLecturer | null> {
    try {
      return await this.service.updateCourseLecturer({
        where: params,
        data: {
          ...data,

          course: {
            connect: data.course,
          },

          lecturer: {
            connect: data.lecturer,
          },
        },
        select: {
          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          lecturer: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CourseLecturer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCourseLecturer(
    @common.Param() params: CourseLecturerWhereUniqueInput
  ): Promise<CourseLecturer | null> {
    try {
      return await this.service.deleteCourseLecturer({
        where: params,
        select: {
          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          lecturer: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
