/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LecturerService } from "../lecturer.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LecturerCreateInput } from "./LecturerCreateInput";
import { Lecturer } from "./Lecturer";
import { LecturerFindManyArgs } from "./LecturerFindManyArgs";
import { LecturerWhereUniqueInput } from "./LecturerWhereUniqueInput";
import { LecturerUpdateInput } from "./LecturerUpdateInput";
import { CourseLecturerFindManyArgs } from "../../courseLecturer/base/CourseLecturerFindManyArgs";
import { CourseLecturer } from "../../courseLecturer/base/CourseLecturer";
import { CourseLecturerWhereUniqueInput } from "../../courseLecturer/base/CourseLecturerWhereUniqueInput";
import { CourseFindManyArgs } from "../../course/base/CourseFindManyArgs";
import { Course } from "../../course/base/Course";
import { CourseWhereUniqueInput } from "../../course/base/CourseWhereUniqueInput";
import { ReviewFindManyArgs } from "../../review/base/ReviewFindManyArgs";
import { Review } from "../../review/base/Review";
import { ReviewWhereUniqueInput } from "../../review/base/ReviewWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LecturerControllerBase {
  constructor(
    protected readonly service: LecturerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Lecturer })
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLecturer(
    @common.Body() data: LecturerCreateInput
  ): Promise<Lecturer> {
    return await this.service.createLecturer({
      data: {
        ...data,

        department: {
          connect: data.department,
        },
      },
      select: {
        createdAt: true,

        department: {
          select: {
            id: true,
          },
        },

        examDifficultyRating: true,
        fullName: true,
        id: true,
        moralityRating: true,
        numberOfReviews: true,
        pressureRating: true,
        rating: true,
        teachingRating: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Lecturer] })
  @ApiNestedQuery(LecturerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async lecturers(@common.Req() request: Request): Promise<Lecturer[]> {
    const args = plainToClass(LecturerFindManyArgs, request.query);
    return this.service.lecturers({
      ...args,
      select: {
        createdAt: true,

        department: {
          select: {
            id: true,
          },
        },

        examDifficultyRating: true,
        fullName: true,
        id: true,
        moralityRating: true,
        numberOfReviews: true,
        pressureRating: true,
        rating: true,
        teachingRating: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Lecturer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async lecturer(
    @common.Param() params: LecturerWhereUniqueInput
  ): Promise<Lecturer | null> {
    const result = await this.service.lecturer({
      where: params,
      select: {
        createdAt: true,

        department: {
          select: {
            id: true,
          },
        },

        examDifficultyRating: true,
        fullName: true,
        id: true,
        moralityRating: true,
        numberOfReviews: true,
        pressureRating: true,
        rating: true,
        teachingRating: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Lecturer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLecturer(
    @common.Param() params: LecturerWhereUniqueInput,
    @common.Body() data: LecturerUpdateInput
  ): Promise<Lecturer | null> {
    try {
      return await this.service.updateLecturer({
        where: params,
        data: {
          ...data,

          department: {
            connect: data.department,
          },
        },
        select: {
          createdAt: true,

          department: {
            select: {
              id: true,
            },
          },

          examDifficultyRating: true,
          fullName: true,
          id: true,
          moralityRating: true,
          numberOfReviews: true,
          pressureRating: true,
          rating: true,
          teachingRating: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Lecturer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLecturer(
    @common.Param() params: LecturerWhereUniqueInput
  ): Promise<Lecturer | null> {
    try {
      return await this.service.deleteLecturer({
        where: params,
        select: {
          createdAt: true,

          department: {
            select: {
              id: true,
            },
          },

          examDifficultyRating: true,
          fullName: true,
          id: true,
          moralityRating: true,
          numberOfReviews: true,
          pressureRating: true,
          rating: true,
          teachingRating: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/courseLecturers")
  @ApiNestedQuery(CourseLecturerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CourseLecturer",
    action: "read",
    possession: "any",
  })
  async findCourseLecturers(
    @common.Req() request: Request,
    @common.Param() params: LecturerWhereUniqueInput
  ): Promise<CourseLecturer[]> {
    const query = plainToClass(CourseLecturerFindManyArgs, request.query);
    const results = await this.service.findCourseLecturers(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        lecturer: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/courseLecturers")
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "update",
    possession: "any",
  })
  async connectCourseLecturers(
    @common.Param() params: LecturerWhereUniqueInput,
    @common.Body() body: CourseLecturerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseLecturers: {
        connect: body,
      },
    };
    await this.service.updateLecturer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/courseLecturers")
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "update",
    possession: "any",
  })
  async updateCourseLecturers(
    @common.Param() params: LecturerWhereUniqueInput,
    @common.Body() body: CourseLecturerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseLecturers: {
        set: body,
      },
    };
    await this.service.updateLecturer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/courseLecturers")
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "update",
    possession: "any",
  })
  async disconnectCourseLecturers(
    @common.Param() params: LecturerWhereUniqueInput,
    @common.Body() body: CourseLecturerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseLecturers: {
        disconnect: body,
      },
    };
    await this.service.updateLecturer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/courses")
  @ApiNestedQuery(CourseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "read",
    possession: "any",
  })
  async findCourses(
    @common.Req() request: Request,
    @common.Param() params: LecturerWhereUniqueInput
  ): Promise<Course[]> {
    const query = plainToClass(CourseFindManyArgs, request.query);
    const results = await this.service.findCourses(params.id, {
      ...query,
      select: {
        capacity: true,
        code: true,
        createdAt: true,
        credit: true,

        department: {
          select: {
            id: true,
          },
        },

        examDate: true,
        grade: true,
        group: true,
        id: true,
        info: true,
        name: true,
        numberOfEnrolled: true,
        numberOfPetitioners: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/courses")
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "update",
    possession: "any",
  })
  async connectCourses(
    @common.Param() params: LecturerWhereUniqueInput,
    @common.Body() body: CourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courses: {
        connect: body,
      },
    };
    await this.service.updateLecturer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/courses")
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "update",
    possession: "any",
  })
  async updateCourses(
    @common.Param() params: LecturerWhereUniqueInput,
    @common.Body() body: CourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courses: {
        set: body,
      },
    };
    await this.service.updateLecturer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/courses")
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "update",
    possession: "any",
  })
  async disconnectCourses(
    @common.Param() params: LecturerWhereUniqueInput,
    @common.Body() body: CourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courses: {
        disconnect: body,
      },
    };
    await this.service.updateLecturer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/reviews")
  @ApiNestedQuery(ReviewFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "read",
    possession: "any",
  })
  async findReviews(
    @common.Req() request: Request,
    @common.Param() params: LecturerWhereUniqueInput
  ): Promise<Review[]> {
    const query = plainToClass(ReviewFindManyArgs, request.query);
    const results = await this.service.findReviews(params.id, {
      ...query,
      select: {
        createdAt: true,
        examDifficultyRating: true,
        id: true,

        lecturer: {
          select: {
            id: true,
          },
        },

        moralityRating: true,
        pressureRating: true,
        rating: true,
        teachingRating: true,
        text: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reviews")
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "update",
    possession: "any",
  })
  async connectReviews(
    @common.Param() params: LecturerWhereUniqueInput,
    @common.Body() body: ReviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviews: {
        connect: body,
      },
    };
    await this.service.updateLecturer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reviews")
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "update",
    possession: "any",
  })
  async updateReviews(
    @common.Param() params: LecturerWhereUniqueInput,
    @common.Body() body: ReviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviews: {
        set: body,
      },
    };
    await this.service.updateLecturer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reviews")
  @nestAccessControl.UseRoles({
    resource: "Lecturer",
    action: "update",
    possession: "any",
  })
  async disconnectReviews(
    @common.Param() params: LecturerWhereUniqueInput,
    @common.Body() body: ReviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviews: {
        disconnect: body,
      },
    };
    await this.service.updateLecturer({
      where: params,
      data,
      select: { id: true },
    });
  }
}
