/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Lecturer, // @ts-ignore
  CourseLecturer, // @ts-ignore
  Course, // @ts-ignore
  Review, // @ts-ignore
  Department,
} from "@prisma/client";

export class LecturerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.LecturerCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.LecturerCountArgs>
  ): Promise<number> {
    return this.prisma.lecturer.count(args);
  }

  async lecturers<T extends Prisma.LecturerFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.LecturerFindManyArgs>
  ): Promise<Lecturer[]> {
    return this.prisma.lecturer.findMany(args);
  }
  async lecturer<T extends Prisma.LecturerFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.LecturerFindUniqueArgs>
  ): Promise<Lecturer | null> {
    return this.prisma.lecturer.findUnique(args);
  }
  async createLecturer<T extends Prisma.LecturerCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.LecturerCreateArgs>
  ): Promise<Lecturer> {
    return this.prisma.lecturer.create<T>(args);
  }
  async updateLecturer<T extends Prisma.LecturerUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.LecturerUpdateArgs>
  ): Promise<Lecturer> {
    return this.prisma.lecturer.update<T>(args);
  }
  async deleteLecturer<T extends Prisma.LecturerDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.LecturerDeleteArgs>
  ): Promise<Lecturer> {
    return this.prisma.lecturer.delete(args);
  }

  async findCourseLecturers(
    parentId: string,
    args: Prisma.CourseLecturerFindManyArgs
  ): Promise<CourseLecturer[]> {
    return this.prisma.lecturer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .courseLecturers(args);
  }

  async findCourses(
    parentId: string,
    args: Prisma.CourseFindManyArgs
  ): Promise<Course[]> {
    return this.prisma.lecturer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .courses(args);
  }

  async findReviews(
    parentId: string,
    args: Prisma.ReviewFindManyArgs
  ): Promise<Review[]> {
    return this.prisma.lecturer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .reviews(args);
  }

  async getDepartment(parentId: string): Promise<Department | null> {
    return this.prisma.lecturer
      .findUnique({
        where: { id: parentId },
      })
      .department();
  }
}
