/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CourseLecturerCreateNestedManyWithoutLecturersInput } from "./CourseLecturerCreateNestedManyWithoutLecturersInput";
import {
  ValidateNested,
  IsOptional,
  IsNumber,
  IsString,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { CourseCreateNestedManyWithoutLecturersInput } from "./CourseCreateNestedManyWithoutLecturersInput";
import { DepartmentWhereUniqueInput } from "../../department/base/DepartmentWhereUniqueInput";
import { ReviewCreateNestedManyWithoutLecturersInput } from "./ReviewCreateNestedManyWithoutLecturersInput";

@InputType()
class LecturerCreateInput {
  @ApiProperty({
    required: false,
    type: () => CourseLecturerCreateNestedManyWithoutLecturersInput,
  })
  @ValidateNested()
  @Type(() => CourseLecturerCreateNestedManyWithoutLecturersInput)
  @IsOptional()
  @Field(() => CourseLecturerCreateNestedManyWithoutLecturersInput, {
    nullable: true,
  })
  courseLecturers?: CourseLecturerCreateNestedManyWithoutLecturersInput;

  @ApiProperty({
    required: false,
    type: () => CourseCreateNestedManyWithoutLecturersInput,
  })
  @ValidateNested()
  @Type(() => CourseCreateNestedManyWithoutLecturersInput)
  @IsOptional()
  @Field(() => CourseCreateNestedManyWithoutLecturersInput, {
    nullable: true,
  })
  courses?: CourseCreateNestedManyWithoutLecturersInput;

  @ApiProperty({
    required: true,
    type: () => DepartmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DepartmentWhereUniqueInput)
  @Field(() => DepartmentWhereUniqueInput)
  department!: DepartmentWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  examDifficultyRating?: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  fullName!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  moralityRating?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  numberOfReviews?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  pressureRating?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rating?: number | null;

  @ApiProperty({
    required: false,
    type: () => ReviewCreateNestedManyWithoutLecturersInput,
  })
  @ValidateNested()
  @Type(() => ReviewCreateNestedManyWithoutLecturersInput)
  @IsOptional()
  @Field(() => ReviewCreateNestedManyWithoutLecturersInput, {
    nullable: true,
  })
  reviews?: ReviewCreateNestedManyWithoutLecturersInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  teachingRating?: number | null;
}

export { LecturerCreateInput as LecturerCreateInput };
