/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CourseLecturerUpdateManyWithoutLecturersInput } from "./CourseLecturerUpdateManyWithoutLecturersInput";
import {
  ValidateNested,
  IsOptional,
  IsNumber,
  IsString,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { CourseUpdateManyWithoutLecturersInput } from "./CourseUpdateManyWithoutLecturersInput";
import { DepartmentWhereUniqueInput } from "../../department/base/DepartmentWhereUniqueInput";
import { ReviewUpdateManyWithoutLecturersInput } from "./ReviewUpdateManyWithoutLecturersInput";

@InputType()
class LecturerUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CourseLecturerUpdateManyWithoutLecturersInput,
  })
  @ValidateNested()
  @Type(() => CourseLecturerUpdateManyWithoutLecturersInput)
  @IsOptional()
  @Field(() => CourseLecturerUpdateManyWithoutLecturersInput, {
    nullable: true,
  })
  courseLecturers?: CourseLecturerUpdateManyWithoutLecturersInput;

  @ApiProperty({
    required: false,
    type: () => CourseUpdateManyWithoutLecturersInput,
  })
  @ValidateNested()
  @Type(() => CourseUpdateManyWithoutLecturersInput)
  @IsOptional()
  @Field(() => CourseUpdateManyWithoutLecturersInput, {
    nullable: true,
  })
  courses?: CourseUpdateManyWithoutLecturersInput;

  @ApiProperty({
    required: false,
    type: () => DepartmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DepartmentWhereUniqueInput)
  @IsOptional()
  @Field(() => DepartmentWhereUniqueInput, {
    nullable: true,
  })
  department?: DepartmentWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  examDifficultyRating?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  moralityRating?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  numberOfReviews?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  pressureRating?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rating?: number | null;

  @ApiProperty({
    required: false,
    type: () => ReviewUpdateManyWithoutLecturersInput,
  })
  @ValidateNested()
  @Type(() => ReviewUpdateManyWithoutLecturersInput)
  @IsOptional()
  @Field(() => ReviewUpdateManyWithoutLecturersInput, {
    nullable: true,
  })
  reviews?: ReviewUpdateManyWithoutLecturersInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  teachingRating?: number | null;
}

export { LecturerUpdateInput as LecturerUpdateInput };
