/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  IsOptional,
  ValidateNested,
  IsNumber,
  IsString,
} from "class-validator";
import { LecturerWhereUniqueInput } from "../../lecturer/base/LecturerWhereUniqueInput";
import { Type } from "class-transformer";
import { ReviewLikeCreateNestedManyWithoutReviewsInput } from "./ReviewLikeCreateNestedManyWithoutReviewsInput";

@InputType()
class ReviewCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  examDifficultyRating?: number | null;

  @ApiProperty({
    required: true,
    type: () => LecturerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => LecturerWhereUniqueInput)
  @Field(() => LecturerWhereUniqueInput)
  lecturer!: LecturerWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  moralityRating?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  pressureRating?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rating?: number | null;

  @ApiProperty({
    required: false,
    type: () => ReviewLikeCreateNestedManyWithoutReviewsInput,
  })
  @ValidateNested()
  @Type(() => ReviewLikeCreateNestedManyWithoutReviewsInput)
  @IsOptional()
  @Field(() => ReviewLikeCreateNestedManyWithoutReviewsInput, {
    nullable: true,
  })
  reviewLikes?: ReviewLikeCreateNestedManyWithoutReviewsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  teachingRating?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  text?: string | null;
}

export { ReviewCreateInput as ReviewCreateInput };
