/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReviewService } from "../review.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReviewCreateInput } from "./ReviewCreateInput";
import { Review } from "./Review";
import { ReviewFindManyArgs } from "./ReviewFindManyArgs";
import { ReviewWhereUniqueInput } from "./ReviewWhereUniqueInput";
import { ReviewUpdateInput } from "./ReviewUpdateInput";
import { ReviewLikeFindManyArgs } from "../../reviewLike/base/ReviewLikeFindManyArgs";
import { ReviewLike } from "../../reviewLike/base/ReviewLike";
import { ReviewLikeWhereUniqueInput } from "../../reviewLike/base/ReviewLikeWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReviewControllerBase {
  constructor(
    protected readonly service: ReviewService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Review })
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createReview(@common.Body() data: ReviewCreateInput): Promise<Review> {
    return await this.service.createReview({
      data: {
        ...data,

        lecturer: {
          connect: data.lecturer,
        },
      },
      select: {
        createdAt: true,
        examDifficultyRating: true,
        id: true,

        lecturer: {
          select: {
            id: true,
          },
        },

        moralityRating: true,
        pressureRating: true,
        rating: true,
        teachingRating: true,
        text: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Review] })
  @ApiNestedQuery(ReviewFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reviews(@common.Req() request: Request): Promise<Review[]> {
    const args = plainToClass(ReviewFindManyArgs, request.query);
    return this.service.reviews({
      ...args,
      select: {
        createdAt: true,
        examDifficultyRating: true,
        id: true,

        lecturer: {
          select: {
            id: true,
          },
        },

        moralityRating: true,
        pressureRating: true,
        rating: true,
        teachingRating: true,
        text: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Review })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async review(
    @common.Param() params: ReviewWhereUniqueInput
  ): Promise<Review | null> {
    const result = await this.service.review({
      where: params,
      select: {
        createdAt: true,
        examDifficultyRating: true,
        id: true,

        lecturer: {
          select: {
            id: true,
          },
        },

        moralityRating: true,
        pressureRating: true,
        rating: true,
        teachingRating: true,
        text: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Review })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateReview(
    @common.Param() params: ReviewWhereUniqueInput,
    @common.Body() data: ReviewUpdateInput
  ): Promise<Review | null> {
    try {
      return await this.service.updateReview({
        where: params,
        data: {
          ...data,

          lecturer: {
            connect: data.lecturer,
          },
        },
        select: {
          createdAt: true,
          examDifficultyRating: true,
          id: true,

          lecturer: {
            select: {
              id: true,
            },
          },

          moralityRating: true,
          pressureRating: true,
          rating: true,
          teachingRating: true,
          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Review })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReview(
    @common.Param() params: ReviewWhereUniqueInput
  ): Promise<Review | null> {
    try {
      return await this.service.deleteReview({
        where: params,
        select: {
          createdAt: true,
          examDifficultyRating: true,
          id: true,

          lecturer: {
            select: {
              id: true,
            },
          },

          moralityRating: true,
          pressureRating: true,
          rating: true,
          teachingRating: true,
          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/reviewLikes")
  @ApiNestedQuery(ReviewLikeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ReviewLike",
    action: "read",
    possession: "any",
  })
  async findReviewLikes(
    @common.Req() request: Request,
    @common.Param() params: ReviewWhereUniqueInput
  ): Promise<ReviewLike[]> {
    const query = plainToClass(ReviewLikeFindManyArgs, request.query);
    const results = await this.service.findReviewLikes(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        like: true,

        review: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reviewLikes")
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "update",
    possession: "any",
  })
  async connectReviewLikes(
    @common.Param() params: ReviewWhereUniqueInput,
    @common.Body() body: ReviewLikeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviewLikes: {
        connect: body,
      },
    };
    await this.service.updateReview({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reviewLikes")
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "update",
    possession: "any",
  })
  async updateReviewLikes(
    @common.Param() params: ReviewWhereUniqueInput,
    @common.Body() body: ReviewLikeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviewLikes: {
        set: body,
      },
    };
    await this.service.updateReview({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reviewLikes")
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "update",
    possession: "any",
  })
  async disconnectReviewLikes(
    @common.Param() params: ReviewWhereUniqueInput,
    @common.Body() body: ReviewLikeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviewLikes: {
        disconnect: body,
      },
    };
    await this.service.updateReview({
      where: params,
      data,
      select: { id: true },
    });
  }
}
